### ISSUE TITLE
EPIC: Dependency Handling for a distributed project setup

### ISSUE THREAD

**Issue by shivenduverma-sap** [open-component-model/ocm-project#100]
Each project / repository inside the open component model setup has dependencies on other modules which are specified in go.mod files. These dependencies can be categorized into 2 categories and each category has its caveats.

1. Common Dependency Handling: There are a few dependencies which are present in all projects, and we refer to specific versions of a dependency. This created 2 problems:
  - Using a specific old version: Anyone trying to develop has to revert the dependencies to older version. Due to the indirect dependency, it might require the correction in ~ 9 projects and all of the projects might not even be on the same version.
     
  - Using different dependency versions for different project. Ideally, they all should be on the same version  to get the same functionality and to avoid detecting failing e2e, etc. tests. Eg: ocm-controller versions
      - https://github.com/open-component-model/mpas-product

  - Proposed Solutions:
    - Have a github actions gather common dependencies from all projects and prevent merging if common dependencies are not on the same/latest version. The versions which should be used should be compiled by the action and stored in a file so that someone who start developing knows the new version they can use locally while developing rather than waiting for the PR to fail and correct before merge

2. ocm cli dependency: The ocm-cli is referred by all projects and apart from the above problem of using different versions, when ever there are changes(refactoring/features) in the CLI, the failures in other projects should be identified and fixed/reported. The failure should not be a landmine for someone starting a new ticket and the failure-fix should be part of the already identified work done on the cli
  - Refactoring: If changes are compatible or not, the only solution to detect breaking changes is to download all projects locally, dependencies in the projects need to refer to local ocm, and then run the tests. It is a task in itself
  - New Feature: There should be a version description/commit indicating the last stable ocm-cli compatible with all projects or use the approach of problem 1
 Proposed Solution:
  - Go recommends modularizing projects and having a single go.mod file. But since each project has to be able to run in bundles {mpas, mpas-prod, mpas-proj, git-cont, replication-cont, ocm-contr, ocm-cli}, {ocm-cli, ocm-controller, ocm-e2e-f}, {ocm-cli} modularization will not work.
  - Following a non-go approach, where we only commit go.mod file and NOT the go.sum(.gitignore) file. Then improve the central CI pipeline to make it a true CI:
    - Consume a linux Golden image from the multi-cloud team, create a docker-file and install all required dependencies to be able to run go mod tidy and go build
    - Use sap-piper-library or any container-execution functionality to run go commands(go mod tidy, go build) in the container
    - The go.sum is generated for the project in the pipeline and commited to git
    - When there is any change in the cli, the go.mod for each project is edited to use the latest ocm-cli, and the pipeline will download the dependencies and add the go.sum and that will trigger the e2e,etc. tests for each project in the corressponding PRs and we would be able to see the failures at a central place. This is true CI
    - If fix is small then fix it, if complicated, create follow up ticket with the logs from the pipeline
    
    For 2. also see open-component-model/ocm-project#121 

Tasks:

- [ ] #34
- [ ] #35

**Comment by morri-son** [comment]
closed this task, #34 and #35 are the follow ups
