### ISSUE TITLE
Replace docker lib dealing with OCI Artifacts in OCI registries (ORAS client?)

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#106]
**User Story**: Introduce ORAS client libraries to deal with OCI Artifacts in OCI registries

**Description**:
Since ORAS is the de facto tool for working with OCI Artifacts, the OCM project should make use of it. ORAS offers a client library in Go that can be used: https://oras.land/docs/client_libraries/overview

**Epic link**:
- open-component-model/ocm-project#120

**Acceptance criteria**:
- [ ] all interaction with OCI registries happens using the ORAS client library

**Related issues**:
- open-component-model/ocm-project#105
- open-component-model/ocm-project#104

**Comment by morri-son** [comment]
@Skarlso , let's park this in favour of some higher priority tasks

**Comment by Skarlso** [comment]
Sure. Do you have some?

**Comment by morri-son** [comment]
@Skarlso : Not really :-). Fabian an me filled the next-up column, but I guess there's room for some other tasks in this sprint, although this one will most-likely take more than two weeks. But I'll move it back to next-up, so once your current tasks are done, just check this and give it a size, then we'll see.

**Comment by Skarlso** [comment]
Okay. I also would like to have some kind of decision on the api design this week even if only a partial one. Like moving the subscription into the ocm controller.

**Comment by morri-son** [comment]
Adding @fabianburth 

@Skarlso , we currently re-think our complete setup of our tool set for lifecycle mgmt and what role the OCM controllers have there. We have multiple teams asking for support, like the ones from DwC we  meet at the workshop this week. So, we need to deep-dive into the current architecture of the controllers again, before we can move on with the new API and CR design.

**Comment by Skarlso** [comment]
https://github.com/open-component-model/ocm/pull/904

**Comment by morri-son** [comment]
@Skarlso was rolled back due to regression, therefore again "open".

**Comment by Skarlso** [comment]
Closed in favour of https://github.com/open-component-model/ocm-project/issues/302
