### ISSUE TITLE
Add attributes to the componentDescriptor resource

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#127]
**What would you like to be added**:
Add attributes name, provider, labels to the componentDescriptor resource

**Why is this needed**:
Currently thecomponentDescriptor resource spec does only contain the version, sources, resources from the v3alpha1.ComponentVersionSpec. Since the term "Component Descriptor" outside a K8s cluster refers to a complete component descriptor of a component version that an "ocm get cv <oci registry>//<component version name>:<version>, it would make sense to use all the same attributes in the componentDescriptor K8s resource even if some of them are not used by downstream controllers.

spec.name, spec.provider, spec.labels are the attributes currently missing. Downloaded, yaml formatted component descriptors can be found here: https://github.com/morri-son/bizx-ocm/tree/main/component-descriptors/2211.19.0

**Comment by Skarlso** [comment]
This is actually now done:

```go
// ComponentDescriptorSpec adds a version to the top level component descriptor definition.
type ComponentDescriptorSpec struct {
	v3alpha1.ComponentVersionSpec `json:",inline"`
	Version                       string `json:"version"`
}

```
