### ISSUE TITLE
Create OCM Library developer documentation

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm-project#132]
**Description**
The library needs a good developer documentation, explaining how it should be used for the most common usecases. There must be example usages for these usecases, to enable developers using the library in an easy to follow approach. Possibly, this documentation could show how the library is used in the OCM CLI.

This documentation needs to be available also on the ocm.software website, similar to the OCM client documentation.

**Comment by morri-son** [comment]
duplicate of https://github.com/open-component-model/ocm-project/issues/124
