### ISSUE TITLE
Project Board Automation(s)

### ISSUE THREAD

**Issue by In-Ko** [open-component-model/ocm-project#133]
**Description**
In order to make working with the new Project Board a bit easier / keep it up-to-date in an automatic fashion, we should have some automation in place which:
- automatically assigns new issues to the Project Board
- adds PRs which are good to be reviewed by others to the Project Board with status "in Review"

**Comment by morri-son** [comment]
Hi @Skarlso , I guess this is related to the caretaker, isn't it? Can it be closed? There's also https://github.com/open-component-model/ocm-project/pull/159 that can maybe linked to this issue. Please check the status and move accordingly.
