### ISSUE TITLE
categorise ComponentReferences as `local` or `external`

### ISSUE THREAD

**Issue by ccwienk** [open-component-model/ocm-project#138]
# Context / Motivation

OCM Component Versions may declare Component-References to other Component-Versions thus describing graphs of Component-Versions that have some semantical coherence.

In the easiest case, all thus-references Component-Versions (represented by their component-descriptors) reside in the same OCM Repository (in which lookup of referenced Component-Versions will always succeed "locally", within the same OCM-Repository the "root" Component-Descriptor was retrieved from).

There may, however, be cases, where Component Versions are stored in difference OCM Repositories, where references are declared between component versions stored in different OCM-Repositories. In such cases, lookup requires a mapping.

Extend `componentReference` by an attribute `relation` to discriminate between component references intended to reference `local` (same OCM Repository) components from `external` ones.

When processing OCM Components from a given OCM Repository, it should be MANDATORY for all component-references declared as `local` to be resolvable in the same OCM Repository that contains the referencing component version.

Whereas component versions referenced as `external` MAY, but do not have to be contained.

**Comment by morri-son** [comment]
closed as mentioned by Christian
