### ISSUE TITLE
Uploader needs clarification

### ISSUE THREAD

**Issue by jensh007** [open-component-model/ocm-project#140]
Uploaders are mentioned at [multiple places](https://github.com/search?q=repo%3Aopen-component-model%2Focm-spec%20uploader&type=code) in the spec, but specification is incomplete:

- doc/specification/formats/artifact_normalization.md lacks a definition what it is
- define an interface of an uploader/downloader
- make clear what is spec and what is implementation
- doc/appendix/README.md mentions that uploaders are not part of the spec

**Comment by morri-son** [comment]
Hi @hilmarf and @mandelsoft , just stumbled upon this older issue which is also mentioned in the OCM spec epic. But maybe it makes sense to check it right now in combination with the work you anyway did around the uploaders? If yes, please pull it into the "Next-Up" column to get it into the worklist.

**Comment by morri-son** [comment]
@hilmarf has this been done as part of https://github.com/open-component-model/ocm/pull/944 or related activities? Can you please check which part of this we can keep and which can move out as solved?

**Comment by morri-son** [comment]
won't fix
