### ISSUE TITLE
artifact_normalization.md needs review

### ISSUE THREAD

**Issue by jensh007** [open-component-model/ocm-project#145]
The section [artifact normalization](https://github.com/open-component-model/ocm-spec/blob/main/doc/specification/formats/artifact_normalization.md) needs review: Many sections of this chapter are not related to normalization.

**Comment by morri-son** [comment]
@jensh007 , I guess this has been fixed with the latest updates we did to the specification. Please check [here](https://github.com/open-component-model/ocm-spec/blob/main/doc/02-processing/03-signing-process.md#signing-process-and-normalization) if this fits your idea of how it should look like.
