### ISSUE TITLE
ociBlob/ociArtifact and ociImage/ociArtifact needs clarification

### ISSUE THREAD

**Issue by jensh007** [open-component-model/ocm-project#148]
From the current spec it is not clear why we need two types and what their difference is. This needs clarification and an example in what situation what type is used. This happens for [artifact types ](https://github.com/open-component-model/ocm-spec/blob/main/doc/appendix/E/README.md)and [access types ](https://github.com/open-component-model/ocm-spec/blob/main/doc/appendix/B/README.md)

**Comment by morri-son** [comment]
Hi @jensh007 , this has been restructured now and can be found here: https://github.com/open-component-model/ocm-spec/blob/main/doc/04-extensions/README.md. Nonetheless I second you in the finding that we should make it better visible why we have the different types.

@mandelsoft , any idea how we can improve the current spec with some additional sentences?

**Comment by morri-son** [comment]
will be done as part of the general discussion about doc/ocm-spec
