### ISSUE TITLE
404 links at https://ocm.software/*

### ISSUE THREAD

**Issue by stb1337** [open-component-model/ocm-project#158]
I found the following 404 links:

https://ocm.software/docs/guides/structuring-software-with-ocm/
- `logical units called [components](https://github.com/open-component-model/ocm-spec/blob/main/doc/specification/elements/README.md#components)`
- `development process new [component versions](https://github.com/open-component-model/ocm-spec/blob/main/doc/specification/elements/README.md#component-versions)`
- `The [Flux OCM controllers](https://ocm.software/docs/guides/controller-reference/overview.md) offer this functionality too`

https://ocm.software/docs/controller-reference/api-reference/ocm-controller/#delivery.ocm.software/v1alpha1.FluxDeployerSpec
- helmReleaseTemplate
[github.com/fluxcd/helm-controller/api/v2beta1.HelmReleaseSpec](https://pkg.go.dev/github.com/fluxcd/helm-controller/api/v2betapkg1#HelmReleaseSpec)	(Optional)

**Comment by hilmarf** [comment]
fixed with https://github.com/open-component-model/ocm-website/pull/308

Final published html pages are now checked - https://github.com/open-component-model/ocm-website/actions/runs/11480219055/job/31948140998
