### ISSUE TITLE
Enable allow-listing-request for  ocm-action a

### ISSUE THREAD

**Issue by robertwol** [open-component-model/ocm-project#171]
We found github action [open-component-model/ocm-action](https://github.com/open-component-model/ocm-action) and like it. But we cannot use it from GitHub Enterprise as it is not allow-listed.
 
Would you be so kind and add the allow-listing-request?

**Comment by stb1337** [comment]
See https://github.tools.sap/github/actions-mirror/pull/516

**Comment by morri-son** [comment]
@robertwol and @stb1337  , does this work now?

**Comment by morri-son** [comment]
just found @stb1337 's email with the required PR: https://github.tools.sap/github/actions-mirror/pull/530. This has been merged, so the action is now on the ACL. Therefore we can close this issue.
