### ISSUE TITLE
Whenever a new version of OCM core is released, the version (+ocm cli documentation) should be updated on the ocm website

### ISSUE THREAD

**Issue by morrison-sap** [open-component-model/ocm-project#172]
**What would you like to be added**:
- [x] Whenever a new version of OCM core is released, the version should be updated on the ocm website
- [x] and the command line interface documentation should also be updated on the ocm website

**Why is this needed**:
Currently this is done manually after each release.

**Comment by hilmarf** [comment]
@morri-son why is the status on the backlog board 'closed' but the issue is 'open'?

**Comment by morri-son** [comment]
Hi @hilmarf , the status of an issue is a different attribute than "open" / "closed". @Skarlso , can the caretaker help to fix this issue and set an issue to "closed" once the status has been set to "closed"?

**Comment by Skarlso** [comment]
@morri-son definitely

**Comment by hilmarf** [comment]
https://github.com/open-component-model/ocm-website/pull/339
