### ISSUE TITLE
Formatting in the client-spec section not correct

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#174]
**What happened**:
On https://ocm.software/docs/cli/cli-reference/add/resources on the bottom of the page the text marker format option has been switched on, but is not switched off, so that all following text also has it. Maybe there is an escape char or something similiar missing somewhere. 

![Bildschirmfoto 2024-04-16 um 09 25 49](https://github.com/open-component-model/ocm-project/assets/67469729/4d24cdcd-ac33-4bf1-a1fb-c5d4b68537f4)

**What you expected to happen**:
Formatting should be correct

**How to reproduce it (as minimally and precisely as possible)**:
Check http://

**Comment by Skarlso** [comment]
Yep, it's in the OCM libraries documentation. I might attempt to fix that.

**Comment by Skarlso** [comment]
`- **<code>noredirect<code>** *bool*`

I missing a code block close.

**Comment by Skarlso** [comment]
Same problem here too. https://github.com/open-component-model/ocm/blob/main/docs/reference/ocm_add_resources.md

**Comment by fabianburth** [comment]
I think this should be fixed with https://github.com/open-component-model/ocm/pull/739, but we probably need a to update the website for it to take effect there.

**Comment by Skarlso** [comment]
We do, yes.
