### ISSUE TITLE
Update OCM Controllers architecture doc

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#175]
**Description**
The https://github.com/open-component-model/ocm-controller/blob/main/docs/architecture.md needs to be updated as several of the controllers have been removed and some CRDs adopted.

**Done Criteria**

- [ ] Internal technical Documentation created/updated
- [ ] Enduser Documentation updated (if applicable

**Comment by morri-son** [comment]
@Skarlso, no more web, but documentation :-)

**Comment by Skarlso** [comment]
Doing this as part of https://github.com/open-component-model/ocm-project/issues/169
