### ISSUE TITLE
Enable upload handler to annotate artifacts

### ISSUE THREAD

**Issue by fabianburth** [open-component-model/ocm-project#190]
**Description**
For traceability reasons, it might be a useful feature to annotate e.g. oci artifacts with the component version identity. This feature should probably be toggle-able. 

**Done Criteria**
- [ ] ...
- [ ] Code has been reviewed by other team members
- [ ] Internal technical Documentation created/updated
- [ ] New / changed code is documented
- [ ] Analysis of existing tests (Unit and Integration)
- [ ] Unit Tests created for new code or existing Unit Tests updated
- [ ] Integration Test Suite updated (includes deletion of existing unnecessary Integration Test and/or creation of new ones if required)
- [ ] Enduser Documentation updated (if applicable)
- [ ] Successful demonstration in Review

**Comment by morri-son** [comment]
fixed by https://github.com/open-component-model/ocm/pull/882

**Comment by mandelsoft** [comment]
https://github.com/open-component-model/ocm/pull/987
