### ISSUE TITLE
Enhance documentation of multi architecture image support

### ISSUE THREAD

**Issue by dee0sap** [open-component-model/ocm-project#191]
**What would you like to be added**:

Currently there is documentation [here](https://github.com/open-component-model/getting-started/blob/b92ba8afb579798dc586f28f8b1f550b7db39a33/step-02/README.md) and [here](https://github.com/open-component-model/ocm-website/blob/b4ac507dcd7c48d250c4a514d452c5d61e093719/content/docs/tutorials/best-practices-with-ocm.md?plain=1#L75)

However this documentation and the code related to dockermulti leads the reader to believe that multi-architecture only exists for images residing in a local docker daemon's registry.   My testing has found this is not the case.

My organization's build infrastructure supports production of multi-architecture images into Artifactory.   OCM seems to have no problem using them and even transporting them, using --copy-resources, from one Artifactory to another.

In the case of a multi-architecture build our infrastructure is creating a 'manifest' image and then an image for each architecture.  This screenshot shows what was produced for version 1.0-454.ffe3f7dgit of hdl-cr-sync.  Note the 3 images with one just containing list.manifest.json.
![image](https://github.com/open-component-model/ocm-project/assets/82829708/5bf8b0e7-3b85-433b-834d-72271be8ce5c)

list.manifest.json is 
```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2197,
         "digest": "sha256:5374a4ce7bb7610b3e7d2e917011e18652b3f98b05149436f597b213eaa567b4",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2196,
         "digest": "sha256:035a1aeb1a80bd31792bd5b8906ca77306f654a198bc55446be8555dd991325b",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      }
   ]
}

```

Both docker and kubernetes know how to work with the 'manifest image'.   e.g.  If my helm chart just refers to the manifest image then depending on the node that my pod is scheduled to k8s will pull down either the arm64 or amd64 image as appropriate.

In my OCM component description a resource entry like this 
```yaml
  - name: hdl-cr-sync-image
    type: ociImage
    version: "1.0-617.0650f83fgit"
    access:
      type: ociArtifact
      imageReference: my-artifactory.com/com.sap.hana.cloud.hdl/hdl-cr-sync:1.0-617.0650f83fgit
```
is sufficient to take advantage of this multi-architecture support.   I can make my component archive and transport it with --copy-resources without issue.

Note that if my component only references the manifest image then after transport all 3 images will be in the destination but the human readable tag will only be present for the manifest image.  For the other images there will just be tags based on the manifest hash.    In the screenshot you can see I have circled the 'hash tags' I am referring to.   Note that OCM is producing those for the manifest image as well as the architecture specific images.

The screenshot below does actually have human readable tags for the architecture specific images as well.   This was produced  after I added resource entries for them to my component.   To be clear, technically everything works for me without the entries for architecture specific images being present.   However for anyone who is just browsing Artifactory with their browser it may be a bit disorientating if the extra tags aren't present.
![image](https://github.com/open-component-model/ocm-project/assets/82829708/4769e3ba-957b-4fa3-9985-ba4ded645ae7)

**Why is this needed**:

The current doc is incomplete and consequently misleading to readers, making them think OCM is less capable than it actually is.

**Comment by dee0sap** [comment]
cc: @morri-son

**Comment by morrison-sap** [comment]
Hi @dee0sap , the tutorial is really only about building multi-arch images locally to be able to add them to component versions without having the need to push them to an OCI registry. And buildx still has the issue of not supporting that (https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/ requires the --push option). One can configure containerd as images storage (https://docs.docker.com/storage/containerd/ and https://docs.docker.com/desktop/containerd/), but that would require changes to the OCM library to interact with the docker daemon to deal with the locally stored images. 

The OCM CLI `add resources` command was always able to support referencing multi-arch images in OCI registries. Do you think we should explicitly enhance the https://github.com/open-component-model/ocm/blob/main/docs/reference/ocm_add_resources.md to make this clear or would it make sense to add the topic of dealing with multi-arch images when creating components in another document?

**Comment by dee0sap** [comment]
Hey @morrison-sap :) 

Give my experience, the tutorial and the ocm_add_resources both need enhancing.

The tutorial should have a statement like 'This is for you if you are doing XXX but it is not for you otherwise because things just work' and add resources doc should say 'if you are using a multi arch then the following will happen'.

Fwiw, my experience was 
- Because the only mention of multi-arch image handing was in the tutorial I thought that perhaps I was stuck
- Since at the time nobody was around to ask for help, I spent a couple hours going through the code trying to understand what special logic was needed for multi-arch and to confirm that I was stuck
- We had our chat on May 17 which left me thinking I still had to take some special steps
- After re-reading my notes and the reviewing the example, I decided to just pretend that things would 'just work' without me doing anything special
- Pleasant surprise , everything did just work.

So what I would like to see are updates in the docs such that the next person who is in my situation skips all of the middle steps.

**Comment by morri-son** [comment]
@n-boshnakov would you be able to support with this issue? In general it is about adding the handling of multi-arch images inside of OCM components to the documentation at two places.

What the documentation mentions [here](https://github.com/open-component-model/getting-started/blob/b92ba8afb579798dc586f28f8b1f550b7db39a33/step-02/README.md) and [here](https://github.com/open-component-model/ocm-website/blob/b4ac507dcd7c48d250c4a514d452c5d61e093719/content/docs/tutorials/best-practices-with-ocm.md?plain=1#L75) is really focussing on BUILDING / CREATING multi-arch images during the build process (locally on the build machine), store it in a local storage and then be able to use it as a resource in an OCM component.

Docker and its buildx command is able to build multi-arch images, but has a hard requirement to push those to an OCI registry (as linked above the docker daemon can be configured to use containerd as storage which solves that issue, but wouldn't directly being a help for our OCM scenario). @dee0sap outlined exactly what should be the purpose: ```So what I would like to see are updates in the docs such that the next person who is in my situation skips all of the middle steps.```:-)

**Comment by morri-son** [comment]
fixed with https://github.com/open-component-model/ocm-website/pull/266
