### ISSUE TITLE
maven hint from pom for uploader

### ISSUE THREAD

**Issue by fabianburth** [open-component-model/ocm-project#200]
**Description**
In order to upload a `localblob` (access type) of type `mavenPackage` (= resource type) to a maven repository, the local blob needs a `hint` containing the GAV (groupid:artifactid:version) under which the blob shall be uploaded to the maven repository.
This `hint` has to correspond with the GAV attributes specified in the POM. If the GAV should be changed, it must be adjusted in the POM file before upload. 
The relevant place to implement this is the StoreBlob method of the maven blob handler (see [here](https://github.com/open-component-model/ocm/blob/main/pkg/contexts/ocm/blobhandler/handlers/generic/maven/blobhandler.go#L33)).

**Done Criteria**
- [ ] ...
- [ ] Code has been reviewed by other team members
- [ ] Internal technical Documentation created/updated
- [ ] New / changed code is documented
- [ ] Analysis of existing tests (Unit and Integration)
- [ ] Unit Tests created for new code or existing Unit Tests updated
- [ ] Integration Test Suite updated (includes deletion of existing unnecessary Integration Test and/or creation of new ones if required)
- [ ] Enduser Documentation updated (if applicable)
- [ ] Successful demonstration in Review

**Comment by Skarlso** [comment]
There is already this thing:
```go

// GetReferenceHint returns the reference hint for the Maven (mvn) artifact.
func (a *AccessSpec) GetReferenceHint(_ accspeccpi.ComponentVersionAccess) string {
	if a.IsPackage() {
		return a.GAV()
	}
	return ""
}

```

Is.. that what is needed here? 🤔

**Comment by Skarlso** [comment]
And 
```go
func Access[M any, P compdesc.ArtifactMetaPointer[M]](ctx ocm.Context, meta P, repo *maven.Repository, groupId, artifactId, version string, opts ...Option) cpi.ArtifactAccess[M] {
	eff := optionutils.EvalOptions(optionutils.WithDefaults(opts, WithCredentialContext(ctx))...)
	if eff.Blob.IsPackage() && eff.Hint == "" {
		eff.Hint = maven.NewCoordinates(groupId, artifactId, version).GAV()
	}
```

Which sets up the Hint for GAV.

**Comment by fabianburth** [comment]
The hint to gav handling for upload should already work. The issue is that the maven POM (which describes a maven package) also contains the gav. So I think currently, if you upload the maven package specifying a hint with a different GAV, the POM is incorrect, because we currently do not adjust it.

**Comment by Skarlso** [comment]
Okay, so it should originate FROM the POM file instead of it being set. Gotcha.

**Comment by fabianburth** [comment]
Actually, I think both:
1) If no hint is provided, read the hint from the POM file.
2) If a hint is provided, adjust the current GAV in the POM file.

**Comment by Skarlso** [comment]
Hmmm. Shouldn’t we rather error if it doesn’t match? Modifying it would mean we modify it before upload but that it wouldn’t change or would change unexpectedly at the local location whatever or wherever that is. The user would be dumbfounded as to why it changed.

**Comment by Skarlso** [comment]
So, like a specific localization step? Wouldn't you have to define a changing source for that to a targeted environment?

**Comment by hilmarf** [comment]
> Now, I'd like to transfer this artifact to another maven repository: https://my.private.maven.repo.org. You don't think it's a valid scenario to allow uploading it under a different GAV such as javapackaging/maven/1.1 in this other repo?

If that means, you're actually changing the groupId (javapackaging), yes I don't think this should ever work. Please raise an error for this. No maven/java project would ever consume that artifact from that repository. groupId + artifactId + version can't be changed.

**Comment by Skarlso** [comment]
>keep the hint attribute and fill it during the creation of the access spec

I think that's what we are doing here right now: https://github.com/open-component-model/ocm/blob/main/api/ocm/elements/artifactblob/mavenblob/resource.go#L19 right? Although not taken from the POM file of course. So instead of this, if the hint is empty, we would have to extract the package, look for the POM file, and get the GAV from there instead of the provided three parameters here `groupId, artifactId, version string,`?


>During upload it should be verified, that this information is correct.

How would that be verified without, extracting the thing and looking for the POM again?

**Comment by fabianburth** [comment]
If I decrypted Uwes message correctly, his suggestion is to work with the hint attribute filled during the creation of the access spec (if given, since it's cheaper). But if you upload, we will always have to look for and analyze the pom to do this verification.

**Comment by Skarlso** [comment]
>fill it during the creation of the access spec from the content of the POM file

_from the content of the POM file_..

So this leads me to believe that he's suggesting to fill it during AccessSpec creation with values taken _from the POM file_.

**Comment by fabianburth** [comment]
Oh yes, you are right. So, the only thing you have to do is verify or fill it during the access spec creation.

**Comment by Skarlso** [comment]
Yeah, that makes sense to me.

**Comment by fabianburth** [comment]
Actually, I was just discussing with @mandelsoft.
There are essentially 2 cases:
1) The maven input spec actually points to an entire maven package containing a POM. In this case, we should already fail to retrieve the maven package from the source maven repository if the GAV is incorrect. Since we use the GAV as hint by default, this should therefore always be correct.
2) The maven input spec points to a specific file within an maven package through specifying GAV+**CE**. In this case, the file could theoretically be e.g. a helm chart and thus, consequently be uploaded to a helm repository. Therefore, it would REQUIRE an explicit hint - BUT this hint would never be the same as in a POM and could therefore not be checked.

So, if we want to support the 2) case, we would have extend the current _maven input and access spec_ with a hint property.  During creation of the input or access spec, we would have to check that the coordinates do not specify a package (so no GAV, but a GAV+CE). There already exists a method `IsPackage`. 

For 1), essentially nothing has to be done.

**Comment by hilmarf** [comment]
but for the 2. case... if it's another type (e.g. helm-chart), shouldn't then the correct other type be used? Instead of misusing 'maven'?

**Comment by Skarlso** [comment]
Yeah, I'm not sure about this second part:
>The maven input spec points to a specific file within an maven package through specifying GAV+CE. In this case, the file could theoretically be e.g. a helm chart and thus, consequently be uploaded to a helm repository.

How would it be a helm chart? I understand that the maven thing could contain anything, but it still would be a MAVEN PACKAGE wouldn't it? So it would contain a POM file.

**Comment by hilmarf** [comment]
it's not the best example (https://repo1.maven.org/maven2/com/github/skwakman/nodejs-maven-binaries/nodejs-maven-binaries/0.10.25/) but theoretically, one could create such versions within a maven-repo without a pom file available - but it's bad practice

**Comment by Skarlso** [comment]
Err.... but the pom file is right there 🤔 https://repo1.maven.org/maven2/com/github/skwakman/nodejs-maven-binaries/nodejs-maven-binaries/0.10.25/nodejs-maven-binaries-0.10.25.pom

**Comment by hilmarf** [comment]
> Err.... but the pom file is right there 🤔 https://repo1.maven.org/maven2/com/github/skwakman/nodejs-maven-binaries/nodejs-maven-binaries/0.10.25/nodejs-maven-binaries-0.10.25.pom

yeah, I know... it's hard to find an example without one (because there is no search criteria for it).
but it is possible: https://stackoverflow.com/questions/11612768/upload-linux-binary-file-to-maven-repository the mentioned command won't create a pom in that repo, it would just contain the binary(rar in the sample)

**Comment by Skarlso** [comment]
Interesting. Sooo I'm guessing those should actually error instead? Like, if we don't find a POM file, we should say, no POM file, please go away?

**Comment by Skarlso** [comment]
## Discussion Conclusion

Two things that need to be done:

### Add `hint` to `AccessSpec` and `InputSpec`

This field will be used in case the type is Maven, and it's **NOT** a package. If both are working, meaning, `IsPackage` is true AND a hint it defined, we will error out. This should be happening only if the type is Maven.

### Check validity of GAV

The GAV information _during upload_ should be verified by fetching the POM file from the package, parsing it and then getting the GAV information from it. If there is _no_ POM file, we will ignore the validation. This should only be happening in the uploader of the Maven implementation.
