### ISSUE TITLE
Add GitHub action to check markdown files for broken links

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#214]
**What would you like to be added**:
Add GitHub action to check markdown files for broken links, e.g. [Add GitHub action to check markdown files for broken links](https://github.com/marketplace/actions/markdown-link-check) or anything else suitable.  Ideally the actions should be executed on every push to main and added to the required tests on a PR, but depending on how long it runs, we may just schedule it.

**Why is this needed**:
To avoid dead links in any of our markdown documentation files in any of the repositories, we should add a Github action that checks for dead links to all repositories.

linked to #161

**Comment by hilmarf** [comment]
e.g. https://github.com/corona-warn-app/cwa-server/blob/main/.github/workflows/markdown-analysis.yml#L27
