### ISSUE TITLE
Resource reconcile failed due to missing url in status

### ISSUE THREAD

**Issue by dee0** [open-component-model/ocm-project#226]
**What happened**:

Reconcile of Resource object failed with 
`"failed to look up component Version: failed to do request: Head \"https://component-descriptors/v2/dmi.csi.sap/dmi-broker/manifests/1.3.0-1126.xb2559b5.17\": dial tcp: lookup component-descriptors on 100.64.0.10:53: no such host",`

ResourceReconciler:reconcile gets this when it is trying to get the resource. This is happening because cv.Status.ReplicatedRepositoryURL is empty string.

**What you expected to happen**:

Reconcile to work 

**How to reproduce it (as minimally and precisely as possible)**:

See discussion [here](https://github.com/open-component-model/ocm-project/issues/68#issuecomment-2200673045)

**Anything else we need to know**:

**Environment**:

See discussion [here](https://github.com/open-component-model/ocm-project/issues/68#issuecomment-2200673045)

**Comment by Skarlso** [comment]
Strange. 🤔 It shouldn't have gotten into this situation since it only tries to deal with component versions that are READY. And all ready component versions have this URL set. 

In any case I'll add an error and reconcile.
