### ISSUE TITLE
Add a clear error message that an ambiguous tag is not supported when adding resources of type `ociImage`

### ISSUE THREAD

**Issue by frewilhelm** [open-component-model/ocm-project#229]
**Description**
 
Adding a resource of type `ociImage` that is tagged with `latest` returns the following error:
 
```bash
$ ocm add resource $CA_ARCHIVE --type ociImage --name image --version ${VERSION} --accessType ociArtifact --reference gcr.io/google_containers/echoserver:latest
processing resource (by options)...
  processing document 1...
    processing index 1
found 1 resource
adding resource ociImage: "name"="image","version"="1.0.0"...
Error: cannot add resource "image"(resource (by options)[1][1]): cannot determine digest: oci artifact "gcr.io/google_containers/echoserver:latest" not found in google_containers/echoserver
```
(inspired by this [example](https://ocm.software/docs/getting-started/getting-started-with-ocm/create-a-component-version/#add-an-image-reference-option-1))

Using the same command without an unambiguously tag, e.g. `1.10`, resolves the error.
 
It is reasonable that it is not possible to add an image with the tag `latest` as a resource, as the tag can never uniquely reference a resource. However, the error message is confusing, as it is not clear that the tag is the problem.
 
___________

That is why I would propose a clear and precise error message that the tag `latest` is not supported.
 
However, one could also argue that this part of the error message `cannot determine digest:` is sufficient to indicate that the resource cannot be referenced unambiguously.

___________

**Done Criteria**
- [ ] ...
- [ ] Code has been reviewed by other team members
- [ ] Internal technical Documentation created/updated
- [ ] New / changed code is documented
- [ ] Analysis of existing tests (Unit and Integration)
- [ ] Unit Tests created for new code or existing Unit Tests updated
- [ ] Integration Test Suite updated (includes deletion of existing unnecessary Integration Test and/or creation of new ones if required)
- [ ] Enduser Documentation updated (if applicable)
- [ ] Successful demonstration in Review

**Comment by morri-son** [comment]
>>However, one could also argue that this part of the error message cannot determine digest: is sufficient to indicate that the resource cannot be referenced unambiguously.

Errors should as clearly as possible state what is the issue and directly point to the cause. It is fine to give more information and an explanation in addition, but at first hand there should be "the tag `latest` is not supported in a resource definition.

**Comment by jakobmoellerdev** [comment]
I took a look here and TBH i dont understand why its impossible to determine a digest. It should be able to resolve from latest to the currently fetched sha256 digest and use that as a reference IMO. WDYT?

**Comment by frewilhelm** [comment]
I mistakenly assumed that `gcr` also resolves a `latest` tag. This is not the case. There is no `latest` tag at all. So the issue is unnecessary.
