### ISSUE TITLE
ocm create component archive with constructor file

### ISSUE THREAD

**Issue by fabianburth** [open-component-model/ocm-project#241]
**Description**
We should enable to create component archives with constructor file.

**Done Criteria**
- [ ] ...
- [ ] Code has been reviewed by other team members
- [ ] Internal technical Documentation created/updated
- [ ] New / changed code is documented
- [ ] Analysis of existing tests (Unit and Integration)
- [ ] Unit Tests created for new code or existing Unit Tests updated
- [ ] Integration Test Suite updated (includes deletion of existing unnecessary Integration Test and/or creation of new ones if required)
- [ ] Enduser Documentation updated (if applicable)
- [ ] Successful demonstration in Review

**Comment by morri-son** [comment]
@fabianburth @mandelsoft Shouldn't we rather think about removing the CA completely and only keep CTFs?

**Comment by morri-son** [comment]
not required anymore as we plan to stick just with CTF
