### ISSUE TITLE
Remove Win i386 as OS architecture from OCM CLI binary build

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#261]
**Description**
Since there is currently no consumer of the Win 386 binaries, the creation of that OS arch from the OCM CLI build should be removed.

**Done Criteria**

- [ ] Code has been reviewed by other team members
- [ ] Analysis of existing tests (Unit and Integration)
- [ ] Unit Tests created for new code or existing Unit Tests updated
- [ ] Integration Test Suite updated (includes deletion of existing unnecessary Integration Test and/or creation of new ones if required)
- [ ] Enduser Documentation updated (if applicable)

**Comment by hilmarf** [comment]
kind of related (at least it touches the same source ;-) ) - https://github.com/open-component-model/ocm/issues/947
