### ISSUE TITLE
Provide Example Components for Deployment with OCM controllers

### ISSUE THREAD

**Issue by fabianburth** [open-component-model/ocm-project#271]
**Description**
To onboard users, we have to provide a walkthrough. Therefore, we need example components containing helm charts, kustomizations and localization rules.

**Comment by morri-son** [comment]
@fabianburth should we add complex components, e.g. a product component just containing references to one or more components that contain the resources to this scenario or would we add such examples only in the documentation area where it is about creating components?

**Comment by Skarlso** [comment]
Work has begun in: https://github.com/open-component-model/podinfo/tree/v1

Right now, Helm based demo resource is added. I'm adding Kustomize in a bit.

**Comment by Skarlso** [comment]
There is some problem with kustomization controller not picking up the artifact that I'm investigating.

**Comment by Skarlso** [comment]
On-hold for now until Localization and Configuration are finished.
