### ISSUE TITLE
EPIC: Prepare Contribution of OpenFlux to community repo

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#283]
**Description**
The work done for [Open Flux](https://github.com/openfluxcd) should be contributed back to the FluxCD project. This Epic covers all related tasks required for that.

**Done Criteria**
- [ ] Code has been reviewed by other team members
- [ ] Internal technical Documentation created/updated
- [ ] New / changed code is documented
- [ ] Analysis of existing tests (Unit and Integration)
- [ ] Unit Tests created for new code or existing Unit Tests updated
- [ ] Integration Test Suite updated (includes deletion of existing unnecessary Integration Test and/or creation of new ones if required)
- [ ] Enduser Documentation updated (if applicable)
- [ ] Successful demonstration in Review

**Comment by Skarlso** [comment]
@Skarlso Paste in the discussion with Stefan about the OCI repo stuff.

**Comment by Skarlso** [comment]
Communication from Stefan regarding the registry implementation details:

```
Gergely Brautigam
  11:04 AM
How would you use the registry to store data? Would you use it as a plain blob store? Or stay on the Layer 0 side? Or use it somehow else? Like proper layering etc?

stefanprodan
  11:34 AM
The Flux OCI Artifacts are single layer, same as Helm. Makes little sense to me to layer yaml files, each layer implies a meta descriptor which at times could take more space than the actual yaml in the layer.
For Timoni artifacts I use 2 layers, one for all CUE definitions and one for the templates, but there is no such separation when you push plain YAMLs like Flux does.

Gergely Brautigam
  12:02 PM
Thanks! That’s good info. Since we are also using the registry approach it would be nice to align with you so in the future we literally just switch over and it should all just work.

stefanprodan
  12:08 PM
What’s important to note here is that source-controller uses a single layer, if your yamls are in more than one layer in some artifact, then it will not work with Flux.
  12:08 PM
You can point Flux to the right layer by specifying a media type Docs here https://fluxcd.io/flux/components/source/ocirepositories/#layer-selector
```
