### ISSUE TITLE
Automatically set issue to / label with "stale" and "rotten" after some time

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#285]
**Description**
Issues not touched for a long time (proposal 180 days) should go to / labeled as "lifecycle/stale". After another period (proposal additional 180 days) in that status they should be set to "lifecycle/rotten". There should be an action similar to https://github.com/actions/stale which handles that.

**Comment by jakobmoellerdev** [comment]
Reopen because we have some more repos to go through 😢
