### ISSUE TITLE
Replace the docker lib with `oras`

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm-project#302]
**What would you like to be added**:

A continuation of https://github.com/open-component-model/ocm-project/issues/106.

Turns out ORAS had some hickups when we tried to introduce it. It handled some parts of the image layering choices based on MediaType incorrectly.

We need to revisit the implementation and try a smaller scale repository approach in which we just replace the interface usage of the `tech/docker` package to minimize breaks.

**Why is this needed**:

**Comment by jakobmoellerdev** [comment]
Needs at least 2 assignees due to complexity of issue

**Comment by Skarlso** [comment]
### Tests

Most important test is making sure that all blobs behind a manifest are actually available and downloadable.

Reproducing steps:

### Description
