### ISSUE TITLE
Prepare Demo with end-2-end scenario for OCM and the OCM controllers

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#329]
**Description**
We should have an end-2-end demo that shows the standard actions on software producer and consumer side and the benefits of using OCM and the tooling on top of it. The demo should cover:

- (creation of) example OCM component containing podinfo application (OCI image + Helm chart)
- Sign component
- Transfer of OCM component to OCI registry (producer registry, public)
- Transfer of OCM component into target environment (consumer registry, private)
- Localization/Configuration
- Deployment

The [secure delivery demo](https://github.com/open-component-model/demo-secure-delivery) pretty much covers all steps, but
- is based on v1 where localisation and configuration are done differently
- contains an aggregated component (Weaveworks GitOps) which need to be checked if not too overwhelming

The existing [demo video](https://share.vidyard.com/watch/NjNrZF2926RUTSUvkU4MdR) took roughly 15 minutes which should the target time.

**Comment by ikhandamirov** [comment]
The issue depends on [#267](https://github.com/open-component-model/ocm-project/issues/267), as the demo has to involve the new replication controller. There should be no workarounds in this regards.

**Comment by Skarlso** [comment]
@ikhandamirov It does not. :)

**Comment by Skarlso** [comment]
The demo uses ocm controller v1 which already has replication. It's not dependent on the replication work for ocm v2.

**Comment by jakobmoellerdev** [comment]
Internal feedback from the demo as is:

> - it starts directly with a slide that shows the workflows, i think that's too much detail for slide 0; rather one more slide that generally shows the setting: publisher publishes software artifacts, consumer wants to import them
> - helmet chart as ociImage? we should use the dedicated helm type for this by now
> - transfer step is shown in tekton, there is talk of a (target) registry - this should be shown / addressed beforehand because that's what it's essentially about; secure transport from A to B
> - only at minute 9 the workflow slide is shown again; i think it would be better if the workflow slide was shown continuously throughout the demo (“here i am right now, this is the next step”), or if it was simply left out of the demo completely and only included in the slidedeck, otherwise it's just a media change that causes unrest and has too little screen time for someone without context knowledge to seriously follow it.
> - I would also leave out weave ui, but you could show briefly with kubectl that a pod came up with the corresponding timestamp, that's good enough in my opinion.

**Comment by morri-son** [comment]
does this mean, we have to stick to v1? As mentioned yesterday, I'm fine with that as from the overall scenario there should not be much difference, and if, we can hide it I guess.

With regards to the WeaveUI: We may remove it from the OCM component, but maybe having a UI and not only kubectl / k9s to show things in the cluster has some advantages. In general the aggregation of components is an important thing to tell, but I'm not sure if the demo needs to do so. WDYT?

**Comment by morri-son** [comment]
> it starts directly with a slide that shows the workflows, i think that's too much detail for slide 0; rather one more slide that generally shows the setting: publisher publishes software artifacts, consumer wants to import them. 

absolutely! One slide that shows the very generic setup on Producer and Consumer side, FAT Firewall in between, Showing the two two distinct domain names that prove the air-gap

> only at minute 9 the workflow slide is shown again; i think it would be better if the workflow slide was shown continuously throughout the demo (“here i am right now, this is the next step”), or if it was simply left out of the demo completely and only included in the slidedeck, otherwise it's just a media change that causes unrest and has too little screen time for someone without context knowledge to seriously follow it.  

also very good point and idea. Use the (very good) workflow slide to structure the walkthrough and bring it to the top before EVERY step. An advantage would also be that we may not need to go to much into technical details (which could overwhelm some in the audience), but can focus on the result. For sure, we need to keep telling a consistent story explaining everything the controllers do, but maybe let some of the complex part out.

> transfer step is shown in tekton, there is talk of a (target) registry - this should be shown / addressed beforehand because that's what it's essentially about; secure transport from A to B

yes, that needs to be mentioned as one of the key features on the "SHIP" slides in the pitch deck, but in general I like the view of the steps in Tekton, as they show what happens on a release from component-constructor.yaml via signing to the OCI registry to final validation. The signing part is not even mention on the "PACK" slide and I will do that.

**Comment by Skarlso** [comment]
we could use gimlet UI or Headlamp too.
https://github.com/gimlet-io/capacitor
https://headlamp.dev/blog/2024/11/07/flux-ui/

**Comment by Skarlso** [comment]
Headlamp might be a bit of an overkill. Capacitor has a smaller footprint. ¯\_(ツ)_/¯
