### ISSUE TITLE
Remove any personal data from the code repositories

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#43]
De-personalize the code: No personal references to developer owned entities should be present. Where ever a placeholder is required, use properly named placeholders. Links to examples should never require a personal login or an account of a project member, everything needs to be publicly available and accessible. If we require to access resources that require authentication, we should create a kind of "bot" or technical user on github (which technically is a personal user, but used differently).

Below are examples from a quick search:
- ~~https://github.com/open-component-model/ocm-controller/blob/main/tilt-settings.yaml.example#L4~~
- ~~https://github.com/open-component-model/git-controller/blob/main/config/samples/mpas_v1alpha1_repository.yaml#L9~~
- ~~https://github.com/open-component-model/git-controller/blob/main/config/samples/delivery_v1alpha1_sync.yaml#L11~~
- ~~https://github.com/open-component-model/git-controller/blob/main/controllers/delivery/sync_controller_test.go#L50~~
- ~~https://github.com/open-component-model/git-controller/blob/main/controllers/delivery/sync_controller_test.go#L75~~
- ~~https://github.com/open-component-model/git-controller/blob/main/controllers/delivery/sync_controller_test.go#L133~~
- ~~https://github.com/open-component-model/git-controller/blob/main/controllers/delivery/sync_controller_test.go#L195~~
- ~~https://github.com/open-component-model/git-controller/blob/main/controllers/delivery/sync_controller_test.go#L225~~
- ~~https://github.com/open-component-model/mpas-product-controller/blob/main/controllers/productdeploymentpipeline_controller_test.go#L41~~
- ~~https://github.com/open-component-model/mpas-product-controller/blob/main/controllers/productdeploymentpipeline_controller_test.go#L45~~
- ~~https://github.com/open-component-model/mpas-product-controller/blob/main/controllers/productdeploymentpipeline_controller_test.go#L60~~
- ~~https://github.com/open-component-model/mpas-product-controller/blob/main/controllers/productdeploymentpipeline_controller_test.go#L65~~
- ~~https://github.com/open-component-model/replication-controller/blob/main/controllers/componentsubscription_controller_test.go#L56~~
- ~~https://github.com/open-component-model/replication-controller/blob/main/controllers/componentsubscription_controller_test.go#L94~~
- ~~https://github.com/open-component-model/replication-controller/blob/main/controllers/componentsubscription_controller_test.go#L131~~
- ~~https://github.com/open-component-model/replication-controller/blob/main/controllers/componentsubscription_controller_test.go#L166~~
- ~~https://github.com/open-component-model/replication-controller/blob/main/pkg/ocm/ocm_test.go#L122~~
- ~~https://github.com/open-component-model/replication-controller/blob/main/pkg/ocm/ocm_test.go#L144~~
- ~~https://github.com/open-component-model/replication-controller/blob/main/pkg/ocm/ocm_test.go#L171~~
- ~~https://github.com/open-component-model/replication-controller/blob/main/pkg/ocm/ocm_test.go#L199~~
- ~~https://github.com/open-component-model/replication-controller/blob/main/pkg/ocm/ocm_test.go#L218~~
- ~~https://github.com/open-component-model/replication-controller/blob/main/pkg/ocm/ocm_test.go#L226~~
- ~~https://github.com/open-component-model/replication-controller/blob/main/pkg/ocm/ocm_test.go#L363~~
- ~~https://github.com/open-component-model/replication-controller/blob/main/pkg/ocm/ocm_test.go#L395~~
- ~~https://github.com/open-component-model/replication-controller/blob/main/pkg/ocm/ocm_test.go#L457~~
- ~~https://github.com/open-component-model/ocm-controller/blob/main/config/samples/componentversion.yaml#L12~~
- ~~https://github.com/open-component-model/ocm-controller/blob/main/examples/basic/cv.yaml#L7~~
- ~~https://github.com/open-component-model/ocm-controller/blob/main/examples/basic/cv.yaml#L11~~
- ~~https://github.com/open-component-model/ocm-controller/blob/main/examples/mapping-with-cue/monolith_component_version.yaml#L7~~
- ~~https://github.com/open-component-model/ocm-controller/blob/main/examples/mapping-with-cue/monolith_component_version.yaml#L11~~
- ~~https://github.com/open-component-model/ocm-controller/blob/main/examples/mapping-with-cue/src/component.yaml#L1~~
- ~~https://github.com/open-component-model/ocm-integrationtest/blob/main/go.mod#L1C26-L1C26~~
- ~~https://github.com/open-component-model/ocm-integrationtest/blob/main/start_docker.sh#L2~~
to name a few

**Comment by morri-son** [comment]
HI @Skarlso , I can still find your name and GitHub name in some of the links, e.g. https://github.com/open-component-model/git-controller/blob/main/config/samples/delivery_v1alpha1_sync.yaml#L11. I propose to do a global search for name/github name/email and replace them by John Doe or Olive OCM, john@doe.com or olive@ocm.software.

**Comment by Skarlso** [comment]
Yes well this isn't merged yet innit?

https://github.com/open-component-model/git-controller/pull/139

**Comment by morri-son** [comment]
@Skarlso , no it is not merged. I just saw the issue in the review column and thought assigned PRs are merged.

**Comment by Skarlso** [comment]
Because it's in review. By you. 🤣 at least those two prs are.

**Comment by morri-son** [comment]
I put the issue back to "in progess"

**Comment by Skarlso** [comment]
Update all links fixed.
