### ISSUE TITLE
Link MPAS demo with recording to the MPAS website : https://ocm.software/mpas/

### ISSUE THREAD

**Issue by robertwol** [open-component-model/ocm-project#47]
this should also decide how to link MPAS documentation to the OCM website.
MPAS Website: https://ocm.software/mpas/
Video: https://sapvideoa35699dc5.hana.ondemand.com/?entry_id=1_2u4p4u7z

**Comment by morri-son** [comment]
done with https://github.com/open-component-model/ocm-website/pull/215/
