### ISSUE TITLE
Create a sustainable way of authorization for all components

### ISSUE THREAD

**Issue by Skarlso** [open-component-model/ocm-project#56]
Right now, the secrets, such as repository access, pull access, tokens, and service accounts, all need to be duplicated into several namespaces because of the component access', and the way controllers work, and objects are located.

For example, several of the secrets and access methods are LocalObjects. And since repositories and configurations and such are created in different namespaces, we have to duplicate their access and secrets for the controllers to find them.

This is a mess right now. Some kind of solution needs to be figured out to bootstrap secrets and create proper access for all controllers.

**Comment by morri-son** [comment]
@Skarlso , I guess we can close this as it was marked on the MPAS board (and now on this new one) as done, or?

**Comment by Skarlso** [comment]
Yeah. :)
