### ISSUE TITLE
ocm controller install -d -s  produces invalid yaml

### ISSUE THREAD

**Issue by dee0** [open-component-model/ocm-project#67]
For bootstrapping the ocm-controller ( and flux ) we need either 
- a valid helm chart, or
- a manifest we can convert into a helm template

With flux this command gives us what we want 
`flux install --export --image-pull-secret $IMAGE_PULL_SECRET --watch-all-namespaces=false -n $NAMESPACE `

The command below seems to be the equivalent for ocm-controller 
ocm controller install -d -s -n $NAMESPACE 

However despite the use of '-s' we have the non yaml below at the start of the output
```
► installing ocm-controller with version latest
► got latest version "v0.18.1"
✔ successfully fetched install file
```

ocm version
{"Major":"0", "Minor":"6", "Patch":"0", "PreRelease":"", "Meta":"", "GitVersion":"0.6.0", "GitCommit":"dfcf27e5f22d83feac7869e0f303c6e6e66f1e8d", "GitTreeState":"", "BuildDate":"2023-12-29T14:31:58Z", "GoVersion":"go1.21.5", "Compiler":"gc", "Platform":"linux/amd64"}

**Comment by Skarlso** [comment]
Ah yes, some of the output is not disabled on yaml output.

**Comment by Skarlso** [comment]
@dee0 So having it display nothing might be off-putting... What do you think about instead, if dryrun is enabled, display things on Stderr but the YAML content goes to Stdout?

**Comment by morri-son** [comment]
@Skarlso and @dee0 , the issue is in status "review". Do the last points of Dan need to be or are already contained in the PR and we can move this to "done"?

**Comment by dee0** [comment]
Hey @morri-son 
Just tried with the latest version and my issues have been addressed.   As far as I am concerned this can be moved to 'done'
