### ISSUE TITLE
Rules in ConfigData can only replace existing nodes in target file, can't add new ones.

### ISSUE THREAD

**Issue by dee0** [open-component-model/ocm-project#71]
This is related to open-component-model/ocm-project#72 

See the comment there about the case where no reasonable default is possible.   open-component-model/ocm-project#72 combined with this make it difficult to manage a large number of config values, particularly when they are organized into a structure.

The hack that I came up with is 
- In ConfigData defaults have an empty target node and a 'defaults' node that has a template provides the actual defaults and that is heavily decorated with the ( &default ) marker.
- Have a rule with the value `(( merge( target, *defaults ) ))

[config.zip](https://github.com/open-component-model/ocm-controller/files/14355905/config.zip)

**Comment by Skarlso** [comment]
We already have an existing patch merge strategy option to handle large and complex cases for configuration.

**Comment by Skarlso** [comment]
Instead of `configRef` define a `patchStrategicMergeRef` that points to an exchange of complex values with a target and a path. The result will be merged based on kustomize merging strategy.

**Comment by dee0sap** [comment]
Believe this case has been fixed with the switch to using yqlib for merging the defaults and the config values.
That said it would be best to add a unit test that confirms it prior to closing this.

**Comment by Skarlso** [comment]
I'll add unit tests for these cases.

**Comment by Skarlso** [comment]
This PR now includes tests for these scenarios because without ocm v0.10.0 these don't work. https://github.com/open-component-model/ocm-controller/pull/425

**Comment by Skarlso** [comment]
This should now have been fixed.
