### ISSUE TITLE
Improve Dangling Resource Cleanup Strategy and Configuration Linting

### ISSUE THREAD

**Issue by robertwol** [open-component-model/ocm-project#77]
## User Story
As a developer or system administrator, I want to ensure that the Open Component Model (OCM) project has an effective strategy for cleaning up unwanted custom resources and a linting mechanism to validate configuration files. This will help prevent the accumulation of dangling resources in the live system and provide better clarity on stalled conditions in controllers. By addressing these issues, we can enhance the overall stability and maintainability of the OCM project.

### Epic link:
- open-component-model/ocm-project#125 

**Potential Tasks:**
- [ ] 1: Implement a garbage collection mechanism for identifying and removing dangling resources in the live system.
- [ ] 2: Define clear guidelines and documentation for identifying stalled conditions in controllers to avoid ambiguity.
- [x] 3: Develop a validation framework for configuration files to ensure their correctness and adherence to specified standards.

**Acceptance criteria**:

**Definition of Done:**
- [ ] The garbage collection mechanism is implemented, tested, and integrated into the OCM project codebase.
- [ ] Guidelines and documentation for identifying stalled conditions in controllers are documented and shared with the OCM community.
- [x] The validation framework for configuration files is developed and integrated, providing meaningful error messages for any configuration file issues.
- [x] Relevant unit tests and integration tests are created and passed successfully.
- [ ] Documentation is updated to include information about the garbage collection mechanism, guidelines for stalled conditions, and the configuration file validation framework.
- [x] The changes are reviewed and approved by the project maintainers.
- [x] The improvements are deployed to the production environment or the appropriate staging/testing environment.

**Related issues**:

**Comment by Skarlso** [comment]
I'm not sure what to do about the garbage collection part. There is not much that we can do. We outsource the deployment to Flux, and set prune. There isn't much else to be done here.

We also have now a configuration validation in place with Schemes and CUE.
