### ISSUE TITLE
Enhance componentVersion CR to add more complex expressions for the SemVer

### ISSUE THREAD

**Issue by morri-son** [open-component-model/ocm-project#78]
To be able to support skipping versions, e.g. because customers already know that a shipped version has unacceptable bugs or customers only want to take every second shipped patch, it should be possible to configure more complex expressions for the SemVer of a componentVersion.

@phoban01 proposes to perhaps augment the existing semver field with a CEL / CUE expression field that could be used to perform complex or regex based matches against versions.

**Comment by morri-son** [comment]
@Skarlso , can you please confirm that this works now as expected (without changing a single line of code? :-))

**Comment by Skarlso** [comment]
@morri-son What about the above comment from @dee0?

Also, do you still want a downgrade? I can add that. That _would_ require a bit of code change. Not much though. :)

**Comment by morri-son** [comment]
@dee0 ,  you mentioned that this should be fixed just using the lib out of the box. Have you been able to test this successfully? @Skarlso  doubts that it works :-)

**Comment by Skarlso** [comment]
So I checked the code, and we did remove some of the things that prevent switching to older version.

Therefor, indeed, this should be working now.
