### ISSUE TITLE
WASM support for Configuration and Localization

### ISSUE THREAD

**Issue by phoban01** [open-component-model/ocm-project#79]
## Description

open-component-model/ocm-controller#195 describes the process for replacing existing Localization and Configuration controllers with WASM transformers.

This is the ticket capturing the work necessary to realize open-component-model/ocm-controller#195 

- [ ]  Choose WASM Runtime (wasmer)
- [ ]  Define an execution contract
- [ ]  Provide standard library WASM binaries for localization and configuration

**Comment by morri-son** [comment]
done with https://github.com/open-component-model/ocm-controller/issues/233 https://github.com/open-component-model/ocm-controller/pull/236
