### ISSUE TITLE
404 links at https://ocm.software/*

### ISSUE THREAD

**Issue by stb1337** [open-component-model/ocm-project#84]
**What happened**:
404 at https://ocm.software/docs/guides/getting-started-with-ocm for:
- `To do this, create a file named [.ocmconfig](https://ocm.software/docs/guides/getting-started-with-ocm/.ocmconfig) in your home directory with the following:`
- `The [component descriptor](https://ocm.software/docs/specification/elements/README.md#component-descriptor) is stored as a yaml file named component-descriptor.yaml. It describes the content of a component version.`
- `Because we use content from the local environment, it is directly packaged into the component archive using the [access method](https://github.com/open-component-model/ocm-spec/blob/main/doc/specification/elements/README.md#artifact-access) of type [local](https://github.com/open-component-model/ocm-spec/blob/main/doc/appendix/B/localBlob.md).`
- `is used to describe the [access method](https://github.com/open-component-model/ocm-spec/blob/main/doc/appendix/B/README.md).`

https://ocm.software/project/about/
- `[OCM Specifications](https://github.com/open-component-model/ocm-spec/tree/main/doc/specification) - The ocm-spec repository contains semantic, formatting, and other types of specifications for OCM.`
- `Read about the [problem statement](https://github.com/open-component-model/ocm-spec/tree/main/doc/introduction) that the OCM set of solutions can help to solve.`
- `Start with the documentation about Model Elements [here](https://github.com/open-component-model/ocm-spec/tree/main/doc/specification/elements).`

https://ocm.software/docs/guides/structuring-software-with-ocm/
- `The [toi installation toolkit](https://github.com/open-component-model/ocm/blob/main/docs/reference/ocm_bootstrap_componentversions_toi-bootstrapping.md) is one tool supporting this`
- `The [Flux OCM controllers](https://ocm.software/docs/guides/getting-started-with-ocm-flux/) offer this functionality too.`

https://ocm.software/docs/controller-reference/api-reference/ocm-controller/#delivery.ocm.software/v1alpha1.ResourceReference

- `Field	Description
ElementMeta
[github.com/open-component-model/ocm/pkg/contexts/ocm/compdesc/versions/ocm.software/v3alpha1.ElementMeta](https://pkg.go.dev/github.com/open-component-model/ocm/pkg/contexts/ocm/compdesc/versions/ocm%5c.software/v3alpha1%5c.ElementMeta)	
(Members of ElementMeta are embedded into this type.)`
- `referencePath
[[]github.com/open-component-model/ocm/pkg/contexts/ocm/compdesc/meta/v1.Identity](https://pkg.go.dev/github.com/open-component-model/ocm/pkg/contexts/ocm/compdesc/meta/v1/Identity)	(Optional)`

**Comment by Skarlso** [comment]
I know how to fix this. There is a more recent implementation of the CRD doc generator. And they have configuration to fix known types for better links.

https://github.com/elastic/crd-ref-docs?tab=readme-ov-file#configuration

I'll use that.

**Comment by Skarlso** [comment]
This link works:

```
https://pkg.go.dev/github.com/open-component-model/ocm/pkg/contexts/ocm/compdesc/meta/v1#Identity
```

As opposed to the generated

```
https://pkg.go.dev/github.com/open-component-model/ocm/pkg/contexts/ocm/compdesc/meta/v1/Identity
```

I'll create a fix for this.

**Comment by Skarlso** [comment]
Nevermind. I just found the settings where the typo is in the doc generator 🤦

**Comment by Skarlso** [comment]
This now works since yesterday: https://ocm.software/docs/controller-reference/api-reference/ocm-controller/#delivery.ocm.software/v1alpha1.ResourceReference
